-- 코드를 입력하세요
SELECT ICECREAM_INFO.FLAVOR 
FROM ICECREAM_INFO
JOIN FIRST_HALF
ON FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR 
WHERE ICECREAM_INFO.INGREDIENT_TYPE="fruit_based" AND FIRST_HALF.TOTAL_ORDER > 3000
ORDER BY FIRST_HALF.TOTAL_ORDER DESC