-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, BB.CATEGORY, BB.TOTAL_SALES
FROM AUTHOR A
INNER JOIN
    (SELECT B.BOOK_ID, B.CATEGORY, B.AUTHOR_ID, SUM(B.PRICE * BS.SALES) AS TOTAL_SALES
    FROM BOOK B
    INNER JOIN (SELECT BOOK_ID, SUM(SALES) AS SALES
                FROM BOOK_SALES
                WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 01
                GROUP BY BOOK_ID) BS
    ON B.BOOK_ID = BS.BOOK_ID
    GROUP BY B.AUTHOR_ID, B.CATEGORY) BB
ON A.AUTHOR_ID = BB.AUTHOR_ID
ORDER BY BB.AUTHOR_ID, BB.CATEGORY DESC